# Generated by Django 5.0 on 2023-12-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
