# Generated by Django 5.0 on 2023-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_changed',
            field=models.DateField(verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_created',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
