# Generated by Django 5.0 on 2023-12-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_data_changed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='adress',
        ),
    ]
